name: tiktok-dl_CI
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Run tests
      run: |
        go test -v ./models

    - name: Upload Unix Artifacts
      if: startsWith(matrix.os, 'ubuntu-')
      uses: actions/upload-artifact@v1
      with:
        name: tiktok-dl_linux
        path: tiktok-dl
        
    - name: Upload Windows Artifacts
      if: startsWith(matrix.os, 'windows-')
      uses: actions/upload-artifact@v1
      with:
        name: tiktok-dl_win64
        path: tiktok-dl.exe
